// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace NguyenPhuongThuyLinh128.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20211006010401_Update_NPTL0128")]
    partial class Update_NPTL0128
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("NguyenPhuongThuyLinh128.Models.NPTL0128", b =>
                {
                    b.Property<int>("NPTLId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NPTLGenre")
                        .HasColumnType("TEXT");

                    b.Property<string>("NPTLName")
                        .HasColumnType("TEXT");

                    b.HasKey("NPTLId");

                    b.ToTable("NPTL0128");
                });

            modelBuilder.Entity("NguyenPhuongThuyLinh128.Models.PersonNPTL128", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("PersonId");

                    b.ToTable("PersonNPTL128");
                });
#pragma warning restore 612, 618
        }
    }
}
